# Generated by Django 6.0.2 on 2026-03-15 16:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'db_table': 'batch',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Company_Name', models.CharField(blank=True, max_length=45)),
                ('Customer_FN', models.CharField(max_length=45)),
                ('Customer_LN', models.CharField(max_length=45)),
                ('Customer_PhoneNum', models.CharField(max_length=20, unique=True)),
                ('Customer_Email', models.CharField(max_length=45, unique=True)),
                ('Customer_StreetNum', models.CharField(max_length=10)),
                ('Customer_StreetName', models.CharField(max_length=45)),
                ('Customer_City', models.CharField(max_length=45)),
                ('Customer_State', models.CharField(blank=True, max_length=2)),
                ('Customer_ZipCode', models.CharField(blank=True, max_length=10)),
                ('Customer_Country', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('Media_ID', models.AutoField(primary_key=True, serialize=False)),
                ('File_Name', models.CharField(max_length=90, unique=True)),
                ('File_Path', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=45, unique=True)),
                ('User_Password', models.CharField(max_length=255)),
                ('User_FN', models.CharField(max_length=45)),
                ('User_LN', models.CharField(max_length=45)),
                ('User_Email', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='MediaMetadata',
            fields=[
                ('MetaData_ID', models.AutoField(primary_key=True, serialize=False)),
                ('File_Type', models.CharField(max_length=45)),
                ('Resolution', models.CharField(blank=True, max_length=45)),
                ('File_Size', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Import_Date', models.DateField(blank=True, null=True)),
                ('HDR', models.BooleanField()),
                ('Frame_Rate', models.CharField(blank=True, max_length=45)),
                ('Codec', models.CharField(blank=True, max_length=45)),
                ('Duration', models.TimeField()),
                ('Aspect_Ratio', models.CharField(blank=True, max_length=45)),
                ('Color_Space', models.CharField(blank=True, max_length=45)),
                ('Media_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='base.media')),
            ],
            options={
                'db_table': 'metadata',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Project_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Project_Name', models.CharField(max_length=90, unique=True)),
                ('Project_Location', models.CharField(blank=True, max_length=90)),
                ('Project_Start_Date', models.DateField()),
                ('Project_End_Date', models.DateField(blank=True, null=True)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='base.customer')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.AddField(
            model_name='media',
            name='Project_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='base.project'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Project_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='base.project'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('Tag_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Tag_Name', models.CharField(max_length=90)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Media_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.media')),
                ('Tag_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tag')),
            ],
            options={
                'db_table': 'media_tags',
            },
        ),
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(related_name='media', through='base.MediaTag', to='base.tag'),
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_user',
                'constraints': [models.UniqueConstraint(fields=('User_ID', 'Project_ID'), name='unique_user_project')],
            },
        ),
        migrations.AddConstraint(
            model_name='mediatag',
            constraint=models.UniqueConstraint(fields=('Tag_ID', 'Media_ID'), name='unique_tag_media'),
        ),
    ]
