# Generated by Django 6.0.2 on 2026-02-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediametadata',
            name='has_color_grade',
            field=models.BooleanField(default=False),
        ),
    ]
