# Generated by Django 6.0.2 on 2026-03-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
         migrations.RunSQL(
            sql="""
            CREATE VIEW IF NOT EXISTS ProjectMediaOverview AS
            SELECT
    		    p.Project_Name,
    		    m.Media_ID,
    		    m.File_Path,
    		    m.Media_Type,
    		    m.Upload_Date
            FROM Project p
            JOIN Media m
            ON p.Project_ID = m.Project_ID;
            """,
            reverse_sql="DROP VIEW IF EXISTS ProjectMediaOverview;"
        ),
            migrations.RunSQL(
            sql="""           
            CREATE VIEW IF NOT EXISTS MediaDetails AS
            SELECT
    		    m.Media_ID,
    		    m.File_Path,
    		    md.Resolution,
    		    md.Duration,
    		    md.Codec
            FROM Media m
            JOIN MediaMetadata md
            ON m.Media_ID = md.Media_ID;
            """,
            reverse_sql="DROP VIEW IF EXISTS MediaDetails;"
        ),

    ]
