# Generated by Django 6.0.2 on 2026-03-24 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_add_some_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='base.batch'),
        ),
    ]
