# Generated by Django 6.0.2 on 2026-03-24 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_media_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='Project_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='base.project'),
        ),
    ]
