# Generated by Django 6.0.2 on 2026-04-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_tag_unique_together_alter_tag_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media Files'},
        ),
        migrations.AlterModelOptions(
            name='mediametadata',
            options={'verbose_name_plural': 'Media Metadata'},
        ),
        migrations.RemoveField(
            model_name='mediametadata',
            name='import_date',
        ),
        migrations.RemoveField(
            model_name='mediametadata',
            name='resolution',
        ),
        migrations.AddField(
            model_name='mediametadata',
            name='aspect_ratio',
            field=models.CharField(blank=True, help_text='Optional source-reported aspect ratio', max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='mediametadata',
            name='bit_rate',
            field=models.BigIntegerField(blank=True, help_text='Bits per second', null=True),
        ),
        migrations.AddField(
            model_name='mediametadata',
            name='codec',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='mediametadata',
            name='color_space',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='mediametadata',
            name='duration',
            field=models.DurationField(blank=True, help_text='Length of media', null=True),
        ),
        migrations.AddField(
            model_name='mediametadata',
            name='frame_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Frames per second, e.g. 23.976', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mediametadata',
            name='hdr',
            field=models.BooleanField(blank=True, help_text='True/False when known, null when unknown', null=True),
        ),
        migrations.AddField(
            model_name='mediametadata',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediametadata',
            name='imported_at',
            field=models.DateTimeField(blank=True, help_text='When this metadata record was imported or created', null=True),
        ),
        migrations.AddField(
            model_name='mediametadata',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street_num',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_path',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='mediametadata',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='mediametadata',
            name='file_type',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='role',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
