# Generated by Django 6.0.2 on 2026-04-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_batch_options_alter_media_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street_num',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zip_code',
        ),
    ]
